Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -44,12 +44,18 @@ jobs:
       #   run: |
       #     tflint -f json --recursive | jq -e '.issues | length == 0' || exit 1
 
-      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration
+      # # Install the latest version of Terraform CLI and configure the Terraform CLI configuration
+      # - name: Install Terraform
+      #   run: |
+      #     wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
+      #     echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
+      #     sudo apt update && sudo apt install terraform
+
       - name: Install Terraform
         run: |
           wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
-          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
-          sudo apt update && sudo apt install terraform
+          sudo apt update || true
+          sudo apt install -y terraform || echo "Terraform installation failed"
 
       # Authenticate via SAKE
       - name: 'Authenticate via SAKE'
